apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-demo
  namespace: socket-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: socket-demo-test
        image: hoang000147/socketdemo:tagVersion
---
apiVersion: v1
kind: Service
metadata:
  name: socket-demo-service
  namespace: socket-demo
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32912
